### ISSUE TITLE
此支付工具类支持jdk1.7吗？

### ISSUE THREAD

**Issue by mingj** [Javen205/IJPay#1]
此支付工具类支持jdk1.7吗？谢谢楼主

**Comment by Javen205** [comment]
目前编译的环境是1.8的，下一个版本会兼容低版本的SDK。

**Comment by mingj** [comment]
感谢 我先自己看看低版本能不能搞 /微笑

**Comment by Javen205** [comment]
@mingj 如果还没有解决，可以使用0.8版本的，目前已支持到1.6版本的JDK。

**Comment by mingj** [comment]
楼主给力，我调了下也是支持jdk1.7，项目能用，但是没想到楼主支持的这么快，谢谢 赞！
