### ISSUE TITLE
SDKUtil signByCertInfo方法不支持5.1.0版本号，代码逻辑bug

### ISSUE THREAD

**Issue by ukle** [Javen205/IJPay#10]
if ("01".equals(signMethod) || "1.0.0".equals(version) || "5.0.1".equals(version)) {
    if ("5.0.0".equals(version) || "1.0.0".equals(version) || "5.0.1".equals(version)) {
    }
    if ("5.1.0".equals(version)) {
    }
}
上述代码，5.1.0版本无法进行签名操作，直接return false 了

**Comment by Javen205** [comment]
signMethod 为 “01” ，这个是固定值，第一层if是会进入的。
所以，以下if也会执行
```
if ("5.1.0".equals(version)) {
}
```

@ukle 请确认

**Comment by ukle** [comment]
> signMethod 为 “01” ，这个是固定值，第一层if是会进入的。
> 所以，以下if也会执行
> 
> ```
> if ("5.1.0".equals(version)) {
> }
> ```
> @ukle 请确认

非对称签名：
01（表示采用 RSA 签名）
HASH 表示散列算法
11：支持散列方式验证 SHA-256
12：支持散列方式验证 SM3
意思是5.1.0版本只支持01非对称签名 是吗？

**Comment by Javen205** [comment]
> > signMethod 为 “01” ，这个是固定值，第一层if是会进入的。
> > 所以，以下if也会执行
> > ```
> > if ("5.1.0".equals(version)) {
> > }
> > ```
> > @ukle 请确认
> 
> 非对称签名：
> 01（表示采用 RSA 签名）
> HASH 表示散列算法
> 11：支持散列方式验证 SHA-256
> 12：支持散列方式验证 SM3
> 意思是5.1.0版本只支持01非对称签名 是吗？

官方提供的案例是5.1.0版本的，配置文件中有提到`请勿改动`。5.1.0版本是否只支持01非对称签名这个你可以咨询一下官方客服。

**Comment by ukle** [comment]
> > > signMethod 为 “01” ，这个是固定值，第一层if是会进入的。
> > > 所以，以下if也会执行
> > > ```
> > > if ("5.1.0".equals(version)) {
> > > }
> > > ```
> > > @ukle 请确认
> > 
> > 
> > 非对称签名：
> > 01（表示采用 RSA 签名）
> > HASH 表示散列算法
> > 11：支持散列方式验证 SHA-256
> > 12：支持散列方式验证 SM3
> > 意思是5.1.0版本只支持01非对称签名 是吗？
> 
> 官方提供的案例是5.1.0版本的，配置文件中有提到`请勿改动`。5.1.0版本是否只支持01非对称签名这个你可以咨询一下官方客服。

我现在使用version5.1.0， 然后signMethod是01，现在又碰到一个问题。验签时validateBySecureKey
if ("11".equals(signMethod)) {
} else if ("12".equals(signMethod)) {
} else {
 return false
}
也就是说01的情况直接验签失败。我走不下去了。
