### ISSUE TITLE
请求帮忙

### ISSUE THREAD

**Issue by qichunlin** [Javen205/IJPay#13]
这个好像是安卓项目吧？我想把你的接口用到我的web项目里面。能加个好友聊聊吗?

**Comment by Javen205** [comment]
- IJPay 是 [JPay](https://github.com/Javen205/JPay) 后端接口SDK，不依赖任何第三方 mvc 框架，仅仅作为工具使用简单快速完成支付模块的开发，可轻松嵌入到任何系统里。
- [JPay](https://github.com/Javen205/JPay) 是简易而不简单的 Android 支付SDK，JPay 是对微信 App 支付、支付宝 App 支付的二次封装,对外提供一个相对简单的接口以及支付结果的回调。

文档以及交流群 [点击这里](https://javen205.gitee.io/ijpay/doc/contact.html)

**Comment by CheeseZhao** [comment]
这东西好像只要后端引用上，开好接口，你web端发请求就好了吧

**Comment by Javen205** [comment]
> 这东西好像只要后端引用上，开好接口，你web端发请求就好了吧

正解 :)
