### ISSUE TITLE
扫码支付是不需要用于的OpenId的吧？

### ISSUE THREAD

**Issue by chosss** [Javen205/IJPay#16]
![image](https://user-images.githubusercontent.com/20724056/61932122-210dba80-afb5-11e9-8cfd-ea5db08cc933.png)
![image](https://user-images.githubusercontent.com/20724056/61932153-3551b780-afb5-11e9-937a-ffddf3c19913.png)

**Comment by Javen205** [comment]
旧的版本是需要 openId 的，新版本此不是必须的，感谢反馈 (*￣︶￣)
