### ISSUE TITLE
请问支付宝app支付quit_url怎么赋值？

### ISSUE THREAD

**Issue by marker-wu** [Javen205/IJPay#17]
请问支付宝app支付quit_url怎么赋值？我看着阿里的sdk中AlipayTradeAppPayModel类里面貌似没有这个参数，而这个参数是必传的。麻烦解答一下，谢谢！
![image](https://user-images.githubusercontent.com/45256940/62098825-9f70a200-b2be-11e9-8d60-cb20293259b7.png)

**Comment by Javen205** [comment]
你截图是 `手机网站支付接口` 而不是 `APP支付相关的接口`  以下是 APP支付`请求参数说明` 文档链接 https://docs.open.alipay.com/204/105465

**Comment by marker-wu** [comment]
好的，谢谢！
请问这套集成方案适用于境外支付场景吗？

**Comment by Javen205** [comment]
暂不支持境外支付场景，微信境外版本只是接口 URL 不同后续会支持，支付宝境外暂时还没有研究同时欢迎贡献代码
