### ISSUE TITLE
WxPayApiConfig 找不到

### ISSUE THREAD

**Issue by TomYule** [Javen205/IJPay#19]
### 版本信息
- IJPay 版本:2.1.1
- 开发环境:
- 支付方式:微信小程序支付

### 报错信息 （注意格式化）

```java

这里粘贴代码或者日志
https://javen205.gitee.io/ijpay/doc/IJPay-Demo.html
文档里面的
```

### 问题描述（包括回显步骤、截图 ）
1、配置支付参数(属性文件或者数据库读取)
2、IJPay微信支付初始化(主要设置通用参数，后面请求接口时不用每次重复设置)
WxPayApiConfig apiConfig = WxPayApiConfig.New()
                .setAppId(appid)
                .setMchId(mch_id)
                .setPaternerKey(partnerKey)
                .setPayModel(PayModel.BUSINESSMODEL);//PayModel.BUSINESSMODEL:普通商户模式  PayModel.SERVICEMODE:服务商模式
WxPayApiConfigKit.setThreadLocalWxPayApiConfig(apiConfig);
更多参数设置请参考 WxPayApiConfig.java

当然支付接口中也不用每次都设置WxPayApiConfig，可以通过WxPayApiConfigKit.getApiConfig(String appId)获取WxPayApiConfig

WxPayApiConfigKit wxPayApiConfig =WxPayApiConfigKit.getApiConfig(appId);
WxPayApiConfig 找不到

### 预期效果描述 
WxPayApiConfig apiConfig = WxPayApiConfig.New()
                .setAppId(appid)
                .setMchId(mch_id)
                .setPaternerKey(partnerKey)
                .setPayModel(PayModel.BUSINESSMODEL);//PayModel.BUSINESSMODEL:普通商户模式  PayModel.SERVICEMODE:服务商模式
WxPayApiConfigKit.setThreadLocalWxPayApiConfig(apiConfig);

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNW 微信公众号开发脚手架交流群：114196246

**Comment by Javen205** [comment]
2.1.1 是最新版本，不用 `WxPayApiConfig` 了，你贴的代码是旧版本的示例。

新版本的示例以及文档后面会陆续更新请先看 IJPay 中的 [IJPay-Demo 来构建参数以及生产签名](https://github.com/Javen205/IJPay/blob/master/IJPay-Demo/src/main/java/com/ijpay/demo/controller/wxpay/WxPayController.java)
