### ISSUE TITLE
新版银联支付怎么弄

### ISSUE THREAD

**Issue by yaoshanli** [Javen205/IJPay#20]
新版的 IJPay中的银联支付怎么做，没看到银联支付的包和demo。

**Comment by Javen205** [comment]
2.x 以后的版本是重构，需要些许时间。如果时间紧急要使用银联支付，可以直接使用 1.2.2 这个版本。
2.x 核心是分模块开发，方便后面扩展其他支付方式。

**Comment by Javen205** [comment]
新版本已发布，使用方式与 1.x 版本相同
