### ISSUE TITLE
支付宝不支持公钥证书加签

### ISSUE THREAD

**Issue by MyOnlyCat** [Javen205/IJPay#21]
### 需求描述

我看实体 `com.ijpay.entity.AliPayBean` 里面并没有配置 支付宝公钥证书 支付宝根证书 以及 应用公钥证书 的配置项,是项目不支持吗?

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNW 微信公众号开发脚手架交流群：114196246

**Comment by Javen205** [comment]
支付宝支付是**私钥加密公钥解决**
详细的配置介绍请 IJPay [参考文档 ](https://javen205.gitee.io/ijpay/guide/config/alipay_config.html)
