### ISSUE TITLE
代码风格

### ISSUE THREAD

**Issue by levin950825** [Javen205/IJPay#24]
### 需求描述

描述越详细越好

是否考虑去掉拦截器和下划线的风格样式，如果是转换XML 可以考虑使用 @Element 注解

**Comment by Javen205** [comment]
微信支付接口请求的 xml 格式就是下划线的风格。如果实体使用驼峰命名，属性上也得使用 XmlElement 注解写一次，还不如直接使用下划线的风格。如果有强制要求，可以重写一套 Model

IJPay SDK 中是没有使用任何拦截器。只是在示例中使用了此方案，当然也可以使用其他方案替代，能达到同样的效果就行。
