### ISSUE TITLE
请求超时无法配置

### ISSUE THREAD

**Issue by kezhou2** [Javen205/IJPay#28]
ERROR sdk.comm.err:158 - 2019-12-25 20:09:52^^alipay.fund.trans.uni.transfer^^null^^192.168.16.3^^Linux^^alipay-sdk-java-4.8.73.ALL^^https://openapi.alipay.com/gateway.do?app_cert_sn=95d8a1b8fb705b15c2a0e22773a859b9&charset=UTF-8&alipa&format=json^_^^_^connect timed out

**Comment by Javen205** [comment]
https://gitee.com/javen205/IJPay/issues/I17C2P
