### ISSUE TITLE
[Request] Official SDK download for UnionPay

### ISSUE THREAD

**Issue by nicktunac** [Javen205/IJPay#3]
Hi Javen,

Could you give me the source of the official SDK of UnionPay for 5.1.0?

Currently, I'm using com.unionpay.acp:1.0.0 but the signing method doesn't have support for SHA 256 encryption.

Thanks and regards,
Nick

**Comment by Javen205** [comment]
@nicktunac 
  I didn't find the SDK of  UnionPay for 5.1.0. What kind of payment do you need?

This is the development platform of unionpay.

https://open.unionpay.com/ajweb/help/file
I hope it will help you.

**Comment by nicktunac** [comment]
@Javen205 

Thanks a lot, I got it already in here https://open.unionpay.com/ajweb/help/file/toDetailPage?id=610&flag=2

Cheers. Closing this issue now.

**Comment by Javen205** [comment]
Welcome
