### ISSUE TITLE
是否可以集成到springmvc项目

### ISSUE THREAD

**Issue by wsxe9988** [Javen205/IJPay#33]
### 需求描述

描述越详细越好

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
完全可以，IJPay 依赖框架当做一个 SDK(JAR) 来用就行
