### ISSUE TITLE
有实现多商户吗

### ISSUE THREAD

**Issue by ttpaigesheng** [Javen205/IJPay#34]
### 需求描述

描述越详细越好

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
首页就有关于多商户多应用的说明哦。

**特别说明：**

- 不依赖任何第三方 MVC 框架，仅仅作为工具使用简单快速完成支付模块的开发，可轻松嵌入到任何系统里。
- 微信支付支持多商户多应用，普通商户模式与服务商商模式当然也支持境外商户、同时支持 Api-v3 与 Api-v2 版本的接口。
- 支付宝支付支持多商户多应用，签名同时支持普通公钥方式与公钥证书方式
