### ISSUE TITLE
获取微信支付公钥返回404

### ISSUE THREAD

**Issue by dominictanggit** [Javen205/IJPay#35]
### 版本信息
- IJPay 版本: 2.6.3
- 开发环境:
- 支付方式: wxPay
- 调用的接口: WxPayApi.getPublicKey

### 报错信息 （注意格式化）
微信用了新的url，WxDomain 添加了
    FRAUD("https://fraud.mch.weixin.qq.com");
但是调用时没使用。
    public static String getPublicKey(Map<String, String> params, String certPath, String certPass) {
        return execution(getReqUrl(WxApiType.GET_PUBLIC_KEY, (WxDomain)null, false), params, certPath, certPass);
    }
```

这里粘贴代码或者日志

```

### 问题描述（包括回显步骤、截图 ）

此项没有详细描述将直接关闭不给予解决

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
使用 execution 自己构建，WxDomain 设置为对应的域名就可以啦

**Comment by Javen205** [comment]
长时间没有回复关闭该 issues
