### ISSUE TITLE
建议读取证书文件的方式调整下

### ISSUE THREAD

**Issue by lengp** [Javen205/IJPay#37]
### 需求描述
打包后读取不到证书信息
描述越详细越好

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
读取不到证书信息应该是你配置的路径有问题，请检查。

如你有更优的方案，请说明你的实现思路或者直接贡献代码。

**Comment by lengp** [comment]
底层都是用这种方式读的文件： new File(getAbsolutePath(path)); 这样后有一个问题，就是打包后读取不到；

new ClassPathResource(KeyPath()); 这种方式读取会不会更好。

也有可能是我打的包有问题

**Comment by MrChen-Fly** [comment]
我们有需求将证书存储在数据库中，能否提供一个InputStream的的方法

**Comment by Javen205** [comment]
你说的是v2版本的接口还是v3版本的接口？ v2 版本的接口已支持

**Comment by evanyangg** [comment]
我这里也遇到了   classpath:/cert 这样读证书 无法读取

**Comment by Javen205** [comment]
@evanyangg 获取到证书的绝对路径，再传入至接口的参数中

**Comment by aaa7636602** [comment]
支持@lengp 的建议， 微信退款证书 有巨大bug，请扩展流的方式读取证书，而不是单一的要求别人传绝对路径，传路径方式，用docker打包部署到服务器，访问不到证书文件：Caused by: java.io.FileNotFoundException: /mydata/apiclient_cert.p12 (No such file or directory)

**Comment by Javen205** [comment]
感谢各位反馈以及贡献代码，目前已都支持 

com.ijpay.core.kit.PayKit#getAbsolutePath
com.ijpay.core.kit.PayKit#getFileToStream
com.ijpay.core.kit.PayKit#getCertFileInputStream

**Comment by JinHong-H** [comment]
支付宝证书存放在项目的resources目录下打包之后仍然读取不到

**Comment by LZJZMT** [comment]
2.8.4版本按以下方式请求亲测已解决
String xmlResult = WxPayApi.orderRefund(false, params, PayKit.getFileToStream(wxPayApiConfig.getCertPath()), wxPayApiConfig.getMchId());
