### ISSUE TITLE
自动更新微信证书

### ISSUE THREAD

**Issue by ToZhanChi** [Javen205/IJPay#39]
### 需求描述

描述越详细越好

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

请问微信V3实现了官方的自动更新微信证书功能吗？如果没有实现，希望有一个自动更新的例子。

**Comment by Javen205** [comment]
官方有提供接口获取证书，IJPay中已实现，文档中示例就是获取证书的示例 https://javen205.gitee.io/ijpay/guide/wxpay/api-v3.html

**Comment by zhanchi88** [comment]
IJPay是有获取证书接口，实现了自动更新证书吗？

**Comment by Javen205** [comment]
没有实现自动更新证书，接口返回证书信息的同时也有返回过期时间。

你可以设置一个定时任务来更新证书。
