### ISSUE TITLE
微信支付v3版退款接口

### ISSUE THREAD

**Issue by shenge43** [Javen205/IJPay#40]
### 需求描述

想咨询下微信支付v3版退款接口以后会更新上去吗？

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
微信 v3 版本支付目前还没有提供退款接口，如果官方提供了退款接口 **IJPay** 会在第一时间支持。

微信官方在没有提供退款接口前，如有退款需求可以直接使用 v2 版本的接口。

**Comment by xy-peng** [comment]
退款已经提供出来了，[文档链接](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_9.shtml)

**Comment by Javen205** [comment]
IJPay 2.7.3 版本已支持微信 v3 版本的退款接口
