### ISSUE TITLE
WxPayApi.getPublicKey 请求路径错误

### ISSUE THREAD

**Issue by yuegongzi** [Javen205/IJPay#45]
### 版本信息
- IJPay 版本:2.7.3
- 开发环境: Mac
- 支付方式: 付款到银行卡
- 调用的接口: WxPayApi.getPublicKey

### 报错信息 （注意格式化）

```
请求 404


```

### 问题描述（包括回显步骤、截图 ）

调用此接口发现 请求的路径为https://api.mch.weixin.qq.com/risk/getpublickey

实际上官方文档的路径为 https://fraud.mch.weixin.qq.com/risk/getpublickey 导致请求404 publickey获取失败

### 预期效果描述 

更换请求路径
### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
感谢反馈，默认使用了 api.mch.weixin.qq.com ，已调整
