### ISSUE TITLE
为什么每个ssl连接都要读取一次证书，而不是把证书缓存起来呢？

### ISSUE THREAD

**Issue by 891877295** [Javen205/IJPay#5]
为什么每个ssl连接都要读取一次证书，而不是把证书缓存起来呢？

**Comment by 891877295** [comment]
读取证书用单例类，证书读取之后放入实例变量中。你觉得怎么样？

**Comment by Javen205** [comment]
按照你的思路，你可以尝试贡献下代码。目前网络请求兼容了okhttp、okhttp3以及HttpURLConnection

**Comment by Javen205** [comment]
@891877295  此需求在1.1.5版本中已添加支持，涉及证书的接口都添加证书文件输入流的重构，不用每次读取证书输入流，证书输入流的缓存开发者自实现即可。
