### ISSUE TITLE
savePlatformCert方法在保存完证书文件应该调用flush

### ISSUE THREAD

**Issue by lalalalovewh** [Javen205/IJPay#54]
### 版本信息
- IJPay 版本:
- 开发环境:
- 支付方式:
- 调用的接口:

### 报错信息 （注意格式化）

![image](https://user-images.githubusercontent.com/49010160/149937162-04bb6e95-3d30-426e-ba78-367798dc7515.png)

### 问题描述（包括回显步骤、截图 ）

此项没有详细描述将直接关闭不给予解决

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
感谢反馈，使用是第三方工具 huTool 底层有调用 flush

<img width="722" alt="image" src="https://user-images.githubusercontent.com/10123694/190881406-738f8ab0-640d-4b21-a5ca-84eae24d4d38.png">
