### ISSUE TITLE
微信支付v3版本支付问题，不知道是不是还没更新代码

### ISSUE THREAD

**Issue by hncdyj123** [Javen205/IJPay#55]
### 版本信息
- IJPay 版本:2.7.9
- 开发环境:
- 支付方式:
- 调用的接口:https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_1.shtml

### 报错信息 （注意格式化）

```
description 为必传参数，而UnifiedOrderModel类里面缺乏最新的V3 api参数，

```

### 问题描述（包括回显步骤、截图 ）
![image](https://user-images.githubusercontent.com/15844006/155933335-5704db6c-65a0-4d0d-9a7f-d82b73abd9b5.png)
![Uploading image.png…]()

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by diyewu** [comment]
在V2和V3包都存在名为UnifiedOrderModel的类
