### ISSUE TITLE
微信支付异步通知时校验：verifyNotify 方法的 SignType 参数没有使用，代码仍然使用 SignType.MD5

### ISSUE THREAD

**Issue by diyewu** [Javen205/IJPay#58]
### 版本信息
- IJPay 版本: 2.8.3
- 开发环境: windows
- 支付方式: 微信支付
- 调用的接口: 支付结果通知 v2

### 报错信息 （注意格式化）

```

public static boolean verifyNotify(Map<String, String> params, String partnerKey, SignType signType) {
        return verifyNotify(params, partnerKey, SignType.MD5, null);
}

```

### 问题描述（包括回显步骤、截图 ）
verifyNotify 方法的 SignType 参数没有使用，代码仍然使用 SignType.MD5，如果使用其他加密方式，没有合适的方法调用，只能重新实现一下verifyNotify（）的逻辑

### 预期效果描述 
使得verifyNotify(Map<String, String> params, String partnerKey, SignType signType) 中的SignType 参数在代码中正常使用

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
已处理
