### ISSUE TITLE
微信支付v3版本的商家转账到零钱demo

### ISSUE THREAD

**Issue by remexsky** [Javen205/IJPay#61]
### 微信支付v3版本的商家转账到零钱

微信支付v3版本的商家转账到零钱的demo没有，建议更新下，微信提现现在都更新到v3了

- 支付平台官方文档
- 是否支持沙箱环境
- 最好能提供测试账号(可以私信)

### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
V3 接口都已经支持了

**Comment by remexsky** [comment]
您发过来的信函主人已经收到,主人将尽快给您回复博学切问所以广知高行微言所以修身

**Comment by remexsky** [comment]
您发过来的信函主人已经收到,主人将尽快给您回复博学切问所以广知高行微言所以修身
