### ISSUE TITLE
分账接收方 Model缺少appid字段

### ISSUE THREAD

**Issue by oceanWu-Jun** [Javen205/IJPay#62]
### 版本信息

- IJPay 版本: 2.9.4

类名ReceiverModel,
通过文档可知,缺少appid字段
![image](https://user-images.githubusercontent.com/59753799/211714389-e0511548-88bc-4d48-ac56-ffccdebe3bf3.png)

**Comment by Javen205** [comment]
v3 分账接口 Model 请使用这个  ProfitSharingModel
