### ISSUE TITLE
可以去掉多余的打印吗?

### ISSUE THREAD

**Issue by 547372621** [Javen205/IJPay#64]
### 版本信息

- IJPay 版本: 2.9.6-17
- 开发环境:
- 支付方式:
- 调用的接口:

### 报错信息 （注意格式化）

```

这里粘贴代码或者日志

```

### 问题描述（包括回显步骤、截图 ）

com/ijpay/core/kit/WxPayKit.java:744 这一行写死了打印

![image](https://user-images.githubusercontent.com/19144018/221779660-38d3ecef-fa29-4347-83bf-2bab5f288457.png)

### 预期效果描述

去掉打印标准输出

### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
感谢反馈，已经去掉了
