### ISSUE TITLE
AliPayApi#wapPay通知URL注释写反啦

### ISSUE THREAD

**Issue by yzengchn** [Javen205/IJPay#65]
### 版本信息

- IJPay 版本: ALL
- 开发环境: *
- 支付方式: *
- 调用的接口: wapPay*

### 报错信息 （注意格式化）

```
/**
	 * WAP支付
	 *
	 * @param response  {@link HttpServletResponse}
	 * @param model     {@link AlipayTradeWapPayModel}
	 * @param returnUrl 异步通知URL
	 * @param notifyUrl 同步通知URL
	 * @throws AlipayApiException 支付宝 Api 异常
	 * @throws IOException        IO 异常
	 */
public static void wapPay*()
```

### 问题描述（包括回显步骤、截图 ）
returnUrl  notifyUrl 注释说明写反，没看源码容易误传参

### 预期效果描述
正确的应该是：returnUrl 为同步；notifyUrl为异步
### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
感谢反馈，已处理

**Comment by GongLe** [comment]
大佬，建议发的版本能有个查阅更新日志的地方，例如CHANGELOG.md
