### ISSUE TITLE
springboot demo中 get接口报错

### ISSUE THREAD

**Issue by rt940910a** [Javen205/IJPay#68]
### 版本信息

- IJPay 版本:
- 开发环境:
- 支付方式:
- 调用的接口:

### 报错信息 （注意格式化）

```
![image](https://github.com/Javen205/IJPay/assets/27659152/10e4856c-eac8-4b0e-90ab-220340164c7f)


这里粘贴代码或者日志

```

### 问题描述（包括回显步骤、截图 ）

此项没有详细描述将直接关闭不给予解决

### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
请确定你的参数是否正确
