### ISSUE TITLE
The method getOutTradeNo() is undefined for the type StringUtils

### ISSUE THREAD

**Issue by apachexc** [Javen205/IJPay#70]
### 版本信息

- IJPay 版本:
- 开发环境:
- 支付方式:
- 调用的接口:

### 报错信息 （注意格式化）
The method getOutTradeNo() is undefined for the type StringUtils

这里粘贴代码或者日志

```

### 问题描述（包括回显步骤、截图 ）

此项没有详细描述将直接关闭不给予解决

### 预期效果描述

### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
请核查你导入的包是不是 `com.ijpay.demo.utils.StringUtils`
