### ISSUE TITLE
还在维护吗

### ISSUE THREAD

**Issue by patience00** [Javen205/IJPay#81]
### 版本信息

- IJPay 版本:2.9.11
- 开发环境:
- 支付方式:
- 调用的接口:

### 报错信息 （注意格式化）
<return_msg><![CDATA[无法将输入源“/body/xml/total_fee”映射到目标字段“标价金额”中，此字段需要一个合法的 64 位有符号整数]]></return_msg>
```

这里粘贴代码或者日志

```

### 问题描述（包括回显步骤、截图 ）

此项没有详细描述将直接关闭不给予解决

### 交流群

- IJPay 让支付触手可及交流群：723992875、864988890
- TNWX 微信系开发脚手架交流群：114196246

**Comment by patience00** [comment]
<return_msg><![CDATA[无法将输入源“/body/xml/total_fee”映射到目标字段“标价金额”中，此字段需要一个合法的 64 位有符号整数]]></return_msg>

**Comment by patience00** [comment]
无法将输入源“/body/xml/total_fee”映射到目标字段“标价金额”中，此字段需要一个合法的 64 位有符号整数

**Comment by wu-sv** [comment]
> 无法将输入源“/body/xml/total_fee”映射到目标字段“标价金额”中，此字段需要一个合法的 64 位有符号整数

这个一看就是金额没有填对，微信的金额的单位都是分
