### ISSUE TITLE
在windows上运行时,加密有些问题

### ISSUE THREAD

**Issue by constanine** [Javen205/IJPay#9]
`src/main/java/com/jpay/secure/RSAUtils.java`中的方法 `public static String encryptByPublicKey(String data,String publicKey,String fillMode)`在windows的cmd中运行,默认是GBK2312,这样加密出来会有问题
`
byte[] dataByte = data.getBytes();
`
应该改为
` data.getBytes("UTF-8");
`
@Javen205

**Comment by Javen205** [comment]
感谢反馈，已记录。

**Comment by constanine** [comment]
附上微信的报错信息
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[参数错误,请检查参数]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[PARAM_ERROR]]></err_code>
<err_code_des><![CDATA[用户真实姓名存在非UTF8字符]]></err_code_des>
<nonce_str><![CDATA[1539222582130]]></nonce_str>
<mch_id><![CDATA[1515170561]]></mch_id>
<partner_trade_no><![CDATA[1539222572663]]></partner_trade_no>
<amount>10</amount>
</xml>
